# Generated by Django 4.0.6 on 2022-08-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Clink Link Above to Read...', max_length=255),
        ),
    ]
